language: node_js
node_js:
  - "7"
  - "6"
  - "4"
script: 
  - "jshint src"
  - "npm test --coverage"
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - "nvm use $TRAVIS_NODE_VERSION"
  - "npm config set loglevel error"
